#ucomment the next line to define a global platform for your project
 platform :osx, '10.12'

target 'LYQianNiu' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'AFNetworking', '~> 3.0’
  pod 'Masonry'
  pod 'SDWebImage'

# Pods for LYQianNiu

  target 'LYQianNiuTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LYQianNiuUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
